apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: resilia-deployment
spec:
  selector:
    matchLabels:
      app: resilia
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: resilia
    spec:
      containers:
      - name: resilia
        image: faruqisan/resilia:latest
        ports:
        - containerPort: 8181
      serviceAccount: put_your_service_account_here
