apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-cli-deployment
spec:
  selector:
    matchLabels:
      app: redis-cli
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: redis-cli
    spec:
      containers:
      - name: redis-cli
        image: itsthenetwork/alpine-redis-cli:latest
        args:
          - "-h"
          - "redis-service.default"
          - "-p"
          - "6379"
          - "ping"
