apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 1; echo `date`; echo -e '*1\r\n$4\r\nPING\r\n' | nc redis-service.default 6379; done"]
