apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilia-deployment
spec:
  selector:
    matchLabels:
      app: resilia
  replicas: 1
  template:
    metadata:
      labels:
        app: resilia
    spec:
      containers:
      - name: resilia
        image: faruqisan/resilia:latest
        args:
          - --in_cluster
          - true
        ports:
        - containerPort: 8181
      serviceAccount: put_your_service_account_here
